@startuml
left to right direction
skinparam shadowing false

:Cu_dan: as Resident
:Bao_ve: as Guard
:Quan_tri_vien: as Admin

' ===== CƯ DÂN =====
Resident --> (Dang_ky_tai_khoan)
Resident --> (Dang_nhap_va_doi_mat_khau)
Resident --> (Dang_ky_xe_va_chon_o_do)
Resident --> (Doi_vi_tri_o_do_Cinema)
Resident --> (Gia_han_ve_thang)
Resident --> (Yeu_cau_chuyen_nhuong_xe)
Resident --> (Tra_cuu_lich_su_vao_ra)

' ===== BẢO VỆ =====
Guard --> (Dang_nhap_tai_khoan)
Guard --> (Giam_sat_camera_cong)
Guard --> (Nhan_dien_bien_so_tu_dong)
Guard --> (Kiem_soat_xe_vao_ra)
Guard --> (Doi_chieu_anh_vao_ra)
Guard --> (Nhap_bien_so_thu_cong)
Guard --> (Xu_ly_canh_bao_Blacklist)
Guard --> (Thu_phi_va_mo_Barrier)

' ===== QUẢN TRỊ VIÊN =====
Admin --> (Dang_nhap_tai_khoan)
Admin --> (Quan_ly_nguoi_dung)
Admin --> (Quan_ly_danh_muc_xe)
Admin --> (Phan_nhom_xe_Blacklist_Whitelist)
Admin --> (Quan_ly_so_do_bai_do)
Admin --> (Phe_duyet_chuyen_nhuong_xe)
Admin --> (Thu_nghiem_nhan_dien_AI)
Admin --> (Bao_cao_doanh_thu_va_xuat_Excel)

@enduml
